name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ENV_NAME: production

jobs:
  build:
    steps:
  - name: Utiliser un secret
    run: echo "Mon secret est ${{ secrets.MY_SECRET }}"
